// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AskTutorEp } from '../src/api/askTutor';
import type { default as _CancelRegistrationEp } from '../src/api/cancelRegistration';
import type { default as _CertificatePdfEp } from '../src/api/certificatePdf';
import type { default as _CompleteLessonEp } from '../src/api/completeLesson';
import type { default as _EnrollSelfEp } from '../src/api/enrollSelf';
import type { default as _GetAcademyEp } from '../src/api/getAcademy';
import type { default as _GetCatalogEp } from '../src/api/getCatalog';
import type { default as _GetCertificateEp } from '../src/api/getCertificate';
import type { default as _GetCourseOverviewEp } from '../src/api/getCourseOverview';
import type { default as _GetHomeEp } from '../src/api/getHome';
import type { default as _GetLeaderboardEp } from '../src/api/getLeaderboard';
import type { default as _GetLessonEp } from '../src/api/getLesson';
import type { default as _GetMeEp } from '../src/api/getMe';
import type { default as _GetPathEp } from '../src/api/getPath';
import type { default as _GetPlayerEp } from '../src/api/getPlayer';
import type { default as _GetTeamEp } from '../src/api/getTeam';
import type { default as _ListLessonCommentsEp } from '../src/api/listLessonComments';
import type { default as _ListMyCertificatesEp } from '../src/api/listMyCertificates';
import type { default as _ListMyLearningEp } from '../src/api/listMyLearning';
import type { default as _ListMyNotificationsEp } from '../src/api/listMyNotifications';
import type { default as _ListSessionsEp } from '../src/api/listSessions';
import type { default as _NudgeReportEp } from '../src/api/nudgeReport';
import type { default as _PostCommentEp } from '../src/api/postComment';
import type { default as _RateCourseEp } from '../src/api/rateCourse';
import type { default as _RegisterSessionEp } from '../src/api/registerSession';
import type { default as _SaveMyProfileEp } from '../src/api/saveMyProfile';
import type { default as _SubmitAssignmentEp } from '../src/api/submitAssignment';
import type { default as _SubmitQuizEp } from '../src/api/submitQuiz';
import type { default as _TrackLessonEp } from '../src/api/trackLesson';
import type { default as _UpdateCommentEp } from '../src/api/updateComment';
import type { default as _UpdateMyNotificationsEp } from '../src/api/updateMyNotifications';
import type { default as _VerifyCertificateEp } from '../src/api/verifyCertificate';

type _AskTutorCfg = typeof _AskTutorEp;
export type AskTutorInputType = NonNullable<_AskTutorCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AskTutorCfg['execute']>[0]['input'];
export type AskTutorOutputType = Awaited<ReturnType<_AskTutorCfg['execute']>>;
export const askTutor = createCaller<AskTutorInputType, AskTutorOutputType>('askTutor');

type _CancelRegistrationCfg = typeof _CancelRegistrationEp;
export type CancelRegistrationInputType = NonNullable<_CancelRegistrationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CancelRegistrationCfg['execute']>[0]['input'];
export type CancelRegistrationOutputType = Awaited<ReturnType<_CancelRegistrationCfg['execute']>>;
export const cancelRegistration = createCaller<CancelRegistrationInputType, CancelRegistrationOutputType>('cancelRegistration');

type _CertificatePdfCfg = typeof _CertificatePdfEp;
export type CertificatePdfInputType = NonNullable<_CertificatePdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CertificatePdfCfg['execute']>[0]['input'];
export type CertificatePdfOutputType = Awaited<ReturnType<_CertificatePdfCfg['execute']>>;
export const certificatePdf = createCaller<CertificatePdfInputType, CertificatePdfOutputType>('certificatePdf');

type _CompleteLessonCfg = typeof _CompleteLessonEp;
export type CompleteLessonInputType = NonNullable<_CompleteLessonCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CompleteLessonCfg['execute']>[0]['input'];
export type CompleteLessonOutputType = Awaited<ReturnType<_CompleteLessonCfg['execute']>>;
export const completeLesson = createCaller<CompleteLessonInputType, CompleteLessonOutputType>('completeLesson');

type _EnrollSelfCfg = typeof _EnrollSelfEp;
export type EnrollSelfInputType = NonNullable<_EnrollSelfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_EnrollSelfCfg['execute']>[0]['input'];
export type EnrollSelfOutputType = Awaited<ReturnType<_EnrollSelfCfg['execute']>>;
export const enrollSelf = createCaller<EnrollSelfInputType, EnrollSelfOutputType>('enrollSelf');

type _GetAcademyCfg = typeof _GetAcademyEp;
export type GetAcademyInputType = NonNullable<_GetAcademyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAcademyCfg['execute']>[0]['input'];
export type GetAcademyOutputType = Awaited<ReturnType<_GetAcademyCfg['execute']>>;
export const getAcademy = createCaller<GetAcademyInputType, GetAcademyOutputType>('getAcademy');

type _GetCatalogCfg = typeof _GetCatalogEp;
export type GetCatalogInputType = NonNullable<_GetCatalogCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCatalogCfg['execute']>[0]['input'];
export type GetCatalogOutputType = Awaited<ReturnType<_GetCatalogCfg['execute']>>;
export const getCatalog = createCaller<GetCatalogInputType, GetCatalogOutputType>('getCatalog');

type _GetCertificateCfg = typeof _GetCertificateEp;
export type GetCertificateInputType = NonNullable<_GetCertificateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCertificateCfg['execute']>[0]['input'];
export type GetCertificateOutputType = Awaited<ReturnType<_GetCertificateCfg['execute']>>;
export const getCertificate = createCaller<GetCertificateInputType, GetCertificateOutputType>('getCertificate');

type _GetCourseOverviewCfg = typeof _GetCourseOverviewEp;
export type GetCourseOverviewInputType = NonNullable<_GetCourseOverviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCourseOverviewCfg['execute']>[0]['input'];
export type GetCourseOverviewOutputType = Awaited<ReturnType<_GetCourseOverviewCfg['execute']>>;
export const getCourseOverview = createCaller<GetCourseOverviewInputType, GetCourseOverviewOutputType>('getCourseOverview');

type _GetHomeCfg = typeof _GetHomeEp;
export type GetHomeInputType = NonNullable<_GetHomeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetHomeCfg['execute']>[0]['input'];
export type GetHomeOutputType = Awaited<ReturnType<_GetHomeCfg['execute']>>;
export const getHome = createCaller<GetHomeInputType, GetHomeOutputType>('getHome');

type _GetLeaderboardCfg = typeof _GetLeaderboardEp;
export type GetLeaderboardInputType = NonNullable<_GetLeaderboardCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLeaderboardCfg['execute']>[0]['input'];
export type GetLeaderboardOutputType = Awaited<ReturnType<_GetLeaderboardCfg['execute']>>;
export const getLeaderboard = createCaller<GetLeaderboardInputType, GetLeaderboardOutputType>('getLeaderboard');

type _GetLessonCfg = typeof _GetLessonEp;
export type GetLessonInputType = NonNullable<_GetLessonCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLessonCfg['execute']>[0]['input'];
export type GetLessonOutputType = Awaited<ReturnType<_GetLessonCfg['execute']>>;
export const getLesson = createCaller<GetLessonInputType, GetLessonOutputType>('getLesson');

type _GetMeCfg = typeof _GetMeEp;
export type GetMeInputType = NonNullable<_GetMeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMeCfg['execute']>[0]['input'];
export type GetMeOutputType = Awaited<ReturnType<_GetMeCfg['execute']>>;
export const getMe = createCaller<GetMeInputType, GetMeOutputType>('getMe');

type _GetPathCfg = typeof _GetPathEp;
export type GetPathInputType = NonNullable<_GetPathCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPathCfg['execute']>[0]['input'];
export type GetPathOutputType = Awaited<ReturnType<_GetPathCfg['execute']>>;
export const getPath = createCaller<GetPathInputType, GetPathOutputType>('getPath');

type _GetPlayerCfg = typeof _GetPlayerEp;
export type GetPlayerInputType = NonNullable<_GetPlayerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPlayerCfg['execute']>[0]['input'];
export type GetPlayerOutputType = Awaited<ReturnType<_GetPlayerCfg['execute']>>;
export const getPlayer = createCaller<GetPlayerInputType, GetPlayerOutputType>('getPlayer');

type _GetTeamCfg = typeof _GetTeamEp;
export type GetTeamInputType = NonNullable<_GetTeamCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetTeamCfg['execute']>[0]['input'];
export type GetTeamOutputType = Awaited<ReturnType<_GetTeamCfg['execute']>>;
export const getTeam = createCaller<GetTeamInputType, GetTeamOutputType>('getTeam');

type _ListLessonCommentsCfg = typeof _ListLessonCommentsEp;
export type ListLessonCommentsInputType = NonNullable<_ListLessonCommentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListLessonCommentsCfg['execute']>[0]['input'];
export type ListLessonCommentsOutputType = Awaited<ReturnType<_ListLessonCommentsCfg['execute']>>;
export const listLessonComments = createCaller<ListLessonCommentsInputType, ListLessonCommentsOutputType>('listLessonComments');

type _ListMyCertificatesCfg = typeof _ListMyCertificatesEp;
export type ListMyCertificatesInputType = NonNullable<_ListMyCertificatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListMyCertificatesCfg['execute']>[0]['input'];
export type ListMyCertificatesOutputType = Awaited<ReturnType<_ListMyCertificatesCfg['execute']>>;
export const listMyCertificates = createCaller<ListMyCertificatesInputType, ListMyCertificatesOutputType>('listMyCertificates');

type _ListMyLearningCfg = typeof _ListMyLearningEp;
export type ListMyLearningInputType = NonNullable<_ListMyLearningCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListMyLearningCfg['execute']>[0]['input'];
export type ListMyLearningOutputType = Awaited<ReturnType<_ListMyLearningCfg['execute']>>;
export const listMyLearning = createCaller<ListMyLearningInputType, ListMyLearningOutputType>('listMyLearning');

type _ListMyNotificationsCfg = typeof _ListMyNotificationsEp;
export type ListMyNotificationsInputType = NonNullable<_ListMyNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListMyNotificationsCfg['execute']>[0]['input'];
export type ListMyNotificationsOutputType = Awaited<ReturnType<_ListMyNotificationsCfg['execute']>>;
export const listMyNotifications = createCaller<ListMyNotificationsInputType, ListMyNotificationsOutputType>('listMyNotifications');

type _ListSessionsCfg = typeof _ListSessionsEp;
export type ListSessionsInputType = NonNullable<_ListSessionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSessionsCfg['execute']>[0]['input'];
export type ListSessionsOutputType = Awaited<ReturnType<_ListSessionsCfg['execute']>>;
export const listSessions = createCaller<ListSessionsInputType, ListSessionsOutputType>('listSessions');

type _NudgeReportCfg = typeof _NudgeReportEp;
export type NudgeReportInputType = NonNullable<_NudgeReportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_NudgeReportCfg['execute']>[0]['input'];
export type NudgeReportOutputType = Awaited<ReturnType<_NudgeReportCfg['execute']>>;
export const nudgeReport = createCaller<NudgeReportInputType, NudgeReportOutputType>('nudgeReport');

type _PostCommentCfg = typeof _PostCommentEp;
export type PostCommentInputType = NonNullable<_PostCommentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PostCommentCfg['execute']>[0]['input'];
export type PostCommentOutputType = Awaited<ReturnType<_PostCommentCfg['execute']>>;
export const postComment = createCaller<PostCommentInputType, PostCommentOutputType>('postComment');

type _RateCourseCfg = typeof _RateCourseEp;
export type RateCourseInputType = NonNullable<_RateCourseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RateCourseCfg['execute']>[0]['input'];
export type RateCourseOutputType = Awaited<ReturnType<_RateCourseCfg['execute']>>;
export const rateCourse = createCaller<RateCourseInputType, RateCourseOutputType>('rateCourse');

type _RegisterSessionCfg = typeof _RegisterSessionEp;
export type RegisterSessionInputType = NonNullable<_RegisterSessionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RegisterSessionCfg['execute']>[0]['input'];
export type RegisterSessionOutputType = Awaited<ReturnType<_RegisterSessionCfg['execute']>>;
export const registerSession = createCaller<RegisterSessionInputType, RegisterSessionOutputType>('registerSession');

type _SaveMyProfileCfg = typeof _SaveMyProfileEp;
export type SaveMyProfileInputType = NonNullable<_SaveMyProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveMyProfileCfg['execute']>[0]['input'];
export type SaveMyProfileOutputType = Awaited<ReturnType<_SaveMyProfileCfg['execute']>>;
export const saveMyProfile = createCaller<SaveMyProfileInputType, SaveMyProfileOutputType>('saveMyProfile');

type _SubmitAssignmentCfg = typeof _SubmitAssignmentEp;
export type SubmitAssignmentInputType = NonNullable<_SubmitAssignmentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitAssignmentCfg['execute']>[0]['input'];
export type SubmitAssignmentOutputType = Awaited<ReturnType<_SubmitAssignmentCfg['execute']>>;
export const submitAssignment = createCaller<SubmitAssignmentInputType, SubmitAssignmentOutputType>('submitAssignment');

type _SubmitQuizCfg = typeof _SubmitQuizEp;
export type SubmitQuizInputType = NonNullable<_SubmitQuizCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitQuizCfg['execute']>[0]['input'];
export type SubmitQuizOutputType = Awaited<ReturnType<_SubmitQuizCfg['execute']>>;
export const submitQuiz = createCaller<SubmitQuizInputType, SubmitQuizOutputType>('submitQuiz');

type _TrackLessonCfg = typeof _TrackLessonEp;
export type TrackLessonInputType = NonNullable<_TrackLessonCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_TrackLessonCfg['execute']>[0]['input'];
export type TrackLessonOutputType = Awaited<ReturnType<_TrackLessonCfg['execute']>>;
export const trackLesson = createCaller<TrackLessonInputType, TrackLessonOutputType>('trackLesson');

type _UpdateCommentCfg = typeof _UpdateCommentEp;
export type UpdateCommentInputType = NonNullable<_UpdateCommentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateCommentCfg['execute']>[0]['input'];
export type UpdateCommentOutputType = Awaited<ReturnType<_UpdateCommentCfg['execute']>>;
export const updateComment = createCaller<UpdateCommentInputType, UpdateCommentOutputType>('updateComment');

type _UpdateMyNotificationsCfg = typeof _UpdateMyNotificationsEp;
export type UpdateMyNotificationsInputType = NonNullable<_UpdateMyNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateMyNotificationsCfg['execute']>[0]['input'];
export type UpdateMyNotificationsOutputType = Awaited<ReturnType<_UpdateMyNotificationsCfg['execute']>>;
export const updateMyNotifications = createCaller<UpdateMyNotificationsInputType, UpdateMyNotificationsOutputType>('updateMyNotifications');

type _VerifyCertificateCfg = typeof _VerifyCertificateEp;
export type VerifyCertificateInputType = NonNullable<_VerifyCertificateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_VerifyCertificateCfg['execute']>[0]['input'];
export type VerifyCertificateOutputType = Awaited<ReturnType<_VerifyCertificateCfg['execute']>>;
export const verifyCertificate = createCaller<VerifyCertificateInputType, VerifyCertificateOutputType>('verifyCertificate');


export const api = {
  askTutor,
  cancelRegistration,
  certificatePdf,
  completeLesson,
  enrollSelf,
  getAcademy,
  getCatalog,
  getCertificate,
  getCourseOverview,
  getHome,
  getLeaderboard,
  getLesson,
  getMe,
  getPath,
  getPlayer,
  getTeam,
  listLessonComments,
  listMyCertificates,
  listMyLearning,
  listMyNotifications,
  listSessions,
  nudgeReport,
  postComment,
  rateCourse,
  registerSession,
  saveMyProfile,
  submitAssignment,
  submitQuiz,
  trackLesson,
  updateComment,
  updateMyNotifications,
  verifyCertificate,
};
