// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AiDraftFeedbackEp } from '../src/api/aiDraftFeedback';
import type { default as _AiGenerateCourseEp } from '../src/api/aiGenerateCourse';
import type { default as _AiGenerateQuizEp } from '../src/api/aiGenerateQuiz';
import type { default as _BootstrapEp } from '../src/api/bootstrap';
import type { default as _BulkUpdatePeopleEp } from '../src/api/bulkUpdatePeople';
import type { default as _CertificatePdfEp } from '../src/api/certificatePdf';
import type { default as _ClearDemoDataEp } from '../src/api/clearDemoData';
import type { default as _DeleteLessonEp } from '../src/api/deleteLesson';
import type { default as _DuplicateCourseEp } from '../src/api/duplicateCourse';
import type { default as _EnrollEp } from '../src/api/enroll';
import type { default as _ExportReportEp } from '../src/api/exportReport';
import type { default as _GetComplianceReportEp } from '../src/api/getComplianceReport';
import type { default as _GetCourseEp } from '../src/api/getCourse';
import type { default as _GetCourseOverviewEp } from '../src/api/getCourseOverview';
import type { default as _GetCourseReportEp } from '../src/api/getCourseReport';
import type { default as _GetEnrollmentEp } from '../src/api/getEnrollment';
import type { default as _GetGroupEp } from '../src/api/getGroup';
import type { default as _GetHomeEp } from '../src/api/getHome';
import type { default as _GetPathEp } from '../src/api/getPath';
import type { default as _GetPersonEp } from '../src/api/getPerson';
import type { default as _GetQuizReportEp } from '../src/api/getQuizReport';
import type { default as _GetReportsEp } from '../src/api/getReports';
import type { default as _GetSessionEp } from '../src/api/getSession';
import type { default as _GetSubmissionEp } from '../src/api/getSubmission';
import type { default as _GradeSubmissionEp } from '../src/api/gradeSubmission';
import type { default as _ImportPeopleEp } from '../src/api/importPeople';
import type { default as _ListCertificatesEp } from '../src/api/listCertificates';
import type { default as _ListDiscussionsEp } from '../src/api/listDiscussions';
import type { default as _ListEnrollmentsEp } from '../src/api/listEnrollments';
import type { default as _ListGroupsEp } from '../src/api/listGroups';
import type { default as _ListNotificationsEp } from '../src/api/listNotifications';
import type { default as _ListPathEnrollmentsEp } from '../src/api/listPathEnrollments';
import type { default as _ListPeopleEp } from '../src/api/listPeople';
import type { default as _ListPersonActivityEp } from '../src/api/listPersonActivity';
import type { default as _ListRulesEp } from '../src/api/listRules';
import type { default as _ListSessionsEp } from '../src/api/listSessions';
import type { default as _ListSubmissionsEp } from '../src/api/listSubmissions';
import type { default as _PreviewRuleEp } from '../src/api/previewRule';
import type { default as _ReorderOutlineEp } from '../src/api/reorderOutline';
import type { default as _RunRuleEp } from '../src/api/runRule';
import type { default as _SaveCategoryEp } from '../src/api/saveCategory';
import type { default as _SaveCommentEp } from '../src/api/saveComment';
import type { default as _SaveCourseEp } from '../src/api/saveCourse';
import type { default as _SaveGroupEp } from '../src/api/saveGroup';
import type { default as _SaveLessonEp } from '../src/api/saveLesson';
import type { default as _SavePathEp } from '../src/api/savePath';
import type { default as _SavePersonEp } from '../src/api/savePerson';
import type { default as _SaveProfileEp } from '../src/api/saveProfile';
import type { default as _SaveRuleEp } from '../src/api/saveRule';
import type { default as _SaveSectionEp } from '../src/api/saveSection';
import type { default as _SaveSessionEp } from '../src/api/saveSession';
import type { default as _SaveSettingsEp } from '../src/api/saveSettings';
import type { default as _SaveTemplateEp } from '../src/api/saveTemplate';
import type { default as _SaveViewEp } from '../src/api/saveView';
import type { default as _SearchEp } from '../src/api/search';
import type { default as _SearchPeopleEp } from '../src/api/searchPeople';
import type { default as _SeedWorkspaceEp } from '../src/api/seedWorkspace';
import type { default as _SendRemindersEp } from '../src/api/sendReminders';
import type { default as _SendTestEmailEp } from '../src/api/sendTestEmail';
import type { default as _SetGroupMembersEp } from '../src/api/setGroupMembers';
import type { default as _UpdateCertificateEp } from '../src/api/updateCertificate';
import type { default as _UpdateEnrollmentsEp } from '../src/api/updateEnrollments';
import type { default as _UpdateNotificationsEp } from '../src/api/updateNotifications';
import type { default as _UpdatePathEnrollmentsEp } from '../src/api/updatePathEnrollments';
import type { default as _UpdateRegistrationsEp } from '../src/api/updateRegistrations';

type _AiDraftFeedbackCfg = typeof _AiDraftFeedbackEp;
export type AiDraftFeedbackInputType = NonNullable<_AiDraftFeedbackCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiDraftFeedbackCfg['execute']>[0]['input'];
export type AiDraftFeedbackOutputType = Awaited<ReturnType<_AiDraftFeedbackCfg['execute']>>;
export const aiDraftFeedback = createCaller<AiDraftFeedbackInputType, AiDraftFeedbackOutputType>('aiDraftFeedback');

type _AiGenerateCourseCfg = typeof _AiGenerateCourseEp;
export type AiGenerateCourseInputType = NonNullable<_AiGenerateCourseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiGenerateCourseCfg['execute']>[0]['input'];
export type AiGenerateCourseOutputType = Awaited<ReturnType<_AiGenerateCourseCfg['execute']>>;
export const aiGenerateCourse = createCaller<AiGenerateCourseInputType, AiGenerateCourseOutputType>('aiGenerateCourse');

type _AiGenerateQuizCfg = typeof _AiGenerateQuizEp;
export type AiGenerateQuizInputType = NonNullable<_AiGenerateQuizCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiGenerateQuizCfg['execute']>[0]['input'];
export type AiGenerateQuizOutputType = Awaited<ReturnType<_AiGenerateQuizCfg['execute']>>;
export const aiGenerateQuiz = createCaller<AiGenerateQuizInputType, AiGenerateQuizOutputType>('aiGenerateQuiz');

type _BootstrapCfg = typeof _BootstrapEp;
export type BootstrapInputType = NonNullable<_BootstrapCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BootstrapCfg['execute']>[0]['input'];
export type BootstrapOutputType = Awaited<ReturnType<_BootstrapCfg['execute']>>;
export const bootstrap = createCaller<BootstrapInputType, BootstrapOutputType>('bootstrap');

type _BulkUpdatePeopleCfg = typeof _BulkUpdatePeopleEp;
export type BulkUpdatePeopleInputType = NonNullable<_BulkUpdatePeopleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BulkUpdatePeopleCfg['execute']>[0]['input'];
export type BulkUpdatePeopleOutputType = Awaited<ReturnType<_BulkUpdatePeopleCfg['execute']>>;
export const bulkUpdatePeople = createCaller<BulkUpdatePeopleInputType, BulkUpdatePeopleOutputType>('bulkUpdatePeople');

type _CertificatePdfCfg = typeof _CertificatePdfEp;
export type CertificatePdfInputType = NonNullable<_CertificatePdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CertificatePdfCfg['execute']>[0]['input'];
export type CertificatePdfOutputType = Awaited<ReturnType<_CertificatePdfCfg['execute']>>;
export const certificatePdf = createCaller<CertificatePdfInputType, CertificatePdfOutputType>('certificatePdf');

type _ClearDemoDataCfg = typeof _ClearDemoDataEp;
export type ClearDemoDataInputType = NonNullable<_ClearDemoDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ClearDemoDataCfg['execute']>[0]['input'];
export type ClearDemoDataOutputType = Awaited<ReturnType<_ClearDemoDataCfg['execute']>>;
export const clearDemoData = createCaller<ClearDemoDataInputType, ClearDemoDataOutputType>('clearDemoData');

type _DeleteLessonCfg = typeof _DeleteLessonEp;
export type DeleteLessonInputType = NonNullable<_DeleteLessonCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteLessonCfg['execute']>[0]['input'];
export type DeleteLessonOutputType = Awaited<ReturnType<_DeleteLessonCfg['execute']>>;
export const deleteLesson = createCaller<DeleteLessonInputType, DeleteLessonOutputType>('deleteLesson');

type _DuplicateCourseCfg = typeof _DuplicateCourseEp;
export type DuplicateCourseInputType = NonNullable<_DuplicateCourseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DuplicateCourseCfg['execute']>[0]['input'];
export type DuplicateCourseOutputType = Awaited<ReturnType<_DuplicateCourseCfg['execute']>>;
export const duplicateCourse = createCaller<DuplicateCourseInputType, DuplicateCourseOutputType>('duplicateCourse');

type _EnrollCfg = typeof _EnrollEp;
export type EnrollInputType = NonNullable<_EnrollCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_EnrollCfg['execute']>[0]['input'];
export type EnrollOutputType = Awaited<ReturnType<_EnrollCfg['execute']>>;
export const enroll = createCaller<EnrollInputType, EnrollOutputType>('enroll');

type _ExportReportCfg = typeof _ExportReportEp;
export type ExportReportInputType = NonNullable<_ExportReportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExportReportCfg['execute']>[0]['input'];
export type ExportReportOutputType = Awaited<ReturnType<_ExportReportCfg['execute']>>;
export const exportReport = createCaller<ExportReportInputType, ExportReportOutputType>('exportReport');

type _GetComplianceReportCfg = typeof _GetComplianceReportEp;
export type GetComplianceReportInputType = NonNullable<_GetComplianceReportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetComplianceReportCfg['execute']>[0]['input'];
export type GetComplianceReportOutputType = Awaited<ReturnType<_GetComplianceReportCfg['execute']>>;
export const getComplianceReport = createCaller<GetComplianceReportInputType, GetComplianceReportOutputType>('getComplianceReport');

type _GetCourseCfg = typeof _GetCourseEp;
export type GetCourseInputType = NonNullable<_GetCourseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCourseCfg['execute']>[0]['input'];
export type GetCourseOutputType = Awaited<ReturnType<_GetCourseCfg['execute']>>;
export const getCourse = createCaller<GetCourseInputType, GetCourseOutputType>('getCourse');

type _GetCourseOverviewCfg = typeof _GetCourseOverviewEp;
export type GetCourseOverviewInputType = NonNullable<_GetCourseOverviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCourseOverviewCfg['execute']>[0]['input'];
export type GetCourseOverviewOutputType = Awaited<ReturnType<_GetCourseOverviewCfg['execute']>>;
export const getCourseOverview = createCaller<GetCourseOverviewInputType, GetCourseOverviewOutputType>('getCourseOverview');

type _GetCourseReportCfg = typeof _GetCourseReportEp;
export type GetCourseReportInputType = NonNullable<_GetCourseReportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCourseReportCfg['execute']>[0]['input'];
export type GetCourseReportOutputType = Awaited<ReturnType<_GetCourseReportCfg['execute']>>;
export const getCourseReport = createCaller<GetCourseReportInputType, GetCourseReportOutputType>('getCourseReport');

type _GetEnrollmentCfg = typeof _GetEnrollmentEp;
export type GetEnrollmentInputType = NonNullable<_GetEnrollmentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetEnrollmentCfg['execute']>[0]['input'];
export type GetEnrollmentOutputType = Awaited<ReturnType<_GetEnrollmentCfg['execute']>>;
export const getEnrollment = createCaller<GetEnrollmentInputType, GetEnrollmentOutputType>('getEnrollment');

type _GetGroupCfg = typeof _GetGroupEp;
export type GetGroupInputType = NonNullable<_GetGroupCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetGroupCfg['execute']>[0]['input'];
export type GetGroupOutputType = Awaited<ReturnType<_GetGroupCfg['execute']>>;
export const getGroup = createCaller<GetGroupInputType, GetGroupOutputType>('getGroup');

type _GetHomeCfg = typeof _GetHomeEp;
export type GetHomeInputType = NonNullable<_GetHomeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetHomeCfg['execute']>[0]['input'];
export type GetHomeOutputType = Awaited<ReturnType<_GetHomeCfg['execute']>>;
export const getHome = createCaller<GetHomeInputType, GetHomeOutputType>('getHome');

type _GetPathCfg = typeof _GetPathEp;
export type GetPathInputType = NonNullable<_GetPathCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPathCfg['execute']>[0]['input'];
export type GetPathOutputType = Awaited<ReturnType<_GetPathCfg['execute']>>;
export const getPath = createCaller<GetPathInputType, GetPathOutputType>('getPath');

type _GetPersonCfg = typeof _GetPersonEp;
export type GetPersonInputType = NonNullable<_GetPersonCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPersonCfg['execute']>[0]['input'];
export type GetPersonOutputType = Awaited<ReturnType<_GetPersonCfg['execute']>>;
export const getPerson = createCaller<GetPersonInputType, GetPersonOutputType>('getPerson');

type _GetQuizReportCfg = typeof _GetQuizReportEp;
export type GetQuizReportInputType = NonNullable<_GetQuizReportCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetQuizReportCfg['execute']>[0]['input'];
export type GetQuizReportOutputType = Awaited<ReturnType<_GetQuizReportCfg['execute']>>;
export const getQuizReport = createCaller<GetQuizReportInputType, GetQuizReportOutputType>('getQuizReport');

type _GetReportsCfg = typeof _GetReportsEp;
export type GetReportsInputType = NonNullable<_GetReportsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReportsCfg['execute']>[0]['input'];
export type GetReportsOutputType = Awaited<ReturnType<_GetReportsCfg['execute']>>;
export const getReports = createCaller<GetReportsInputType, GetReportsOutputType>('getReports');

type _GetSessionCfg = typeof _GetSessionEp;
export type GetSessionInputType = NonNullable<_GetSessionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSessionCfg['execute']>[0]['input'];
export type GetSessionOutputType = Awaited<ReturnType<_GetSessionCfg['execute']>>;
export const getSession = createCaller<GetSessionInputType, GetSessionOutputType>('getSession');

type _GetSubmissionCfg = typeof _GetSubmissionEp;
export type GetSubmissionInputType = NonNullable<_GetSubmissionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSubmissionCfg['execute']>[0]['input'];
export type GetSubmissionOutputType = Awaited<ReturnType<_GetSubmissionCfg['execute']>>;
export const getSubmission = createCaller<GetSubmissionInputType, GetSubmissionOutputType>('getSubmission');

type _GradeSubmissionCfg = typeof _GradeSubmissionEp;
export type GradeSubmissionInputType = NonNullable<_GradeSubmissionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GradeSubmissionCfg['execute']>[0]['input'];
export type GradeSubmissionOutputType = Awaited<ReturnType<_GradeSubmissionCfg['execute']>>;
export const gradeSubmission = createCaller<GradeSubmissionInputType, GradeSubmissionOutputType>('gradeSubmission');

type _ImportPeopleCfg = typeof _ImportPeopleEp;
export type ImportPeopleInputType = NonNullable<_ImportPeopleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ImportPeopleCfg['execute']>[0]['input'];
export type ImportPeopleOutputType = Awaited<ReturnType<_ImportPeopleCfg['execute']>>;
export const importPeople = createCaller<ImportPeopleInputType, ImportPeopleOutputType>('importPeople');

type _ListCertificatesCfg = typeof _ListCertificatesEp;
export type ListCertificatesInputType = NonNullable<_ListCertificatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListCertificatesCfg['execute']>[0]['input'];
export type ListCertificatesOutputType = Awaited<ReturnType<_ListCertificatesCfg['execute']>>;
export const listCertificates = createCaller<ListCertificatesInputType, ListCertificatesOutputType>('listCertificates');

type _ListDiscussionsCfg = typeof _ListDiscussionsEp;
export type ListDiscussionsInputType = NonNullable<_ListDiscussionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListDiscussionsCfg['execute']>[0]['input'];
export type ListDiscussionsOutputType = Awaited<ReturnType<_ListDiscussionsCfg['execute']>>;
export const listDiscussions = createCaller<ListDiscussionsInputType, ListDiscussionsOutputType>('listDiscussions');

type _ListEnrollmentsCfg = typeof _ListEnrollmentsEp;
export type ListEnrollmentsInputType = NonNullable<_ListEnrollmentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListEnrollmentsCfg['execute']>[0]['input'];
export type ListEnrollmentsOutputType = Awaited<ReturnType<_ListEnrollmentsCfg['execute']>>;
export const listEnrollments = createCaller<ListEnrollmentsInputType, ListEnrollmentsOutputType>('listEnrollments');

type _ListGroupsCfg = typeof _ListGroupsEp;
export type ListGroupsInputType = NonNullable<_ListGroupsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListGroupsCfg['execute']>[0]['input'];
export type ListGroupsOutputType = Awaited<ReturnType<_ListGroupsCfg['execute']>>;
export const listGroups = createCaller<ListGroupsInputType, ListGroupsOutputType>('listGroups');

type _ListNotificationsCfg = typeof _ListNotificationsEp;
export type ListNotificationsInputType = NonNullable<_ListNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListNotificationsCfg['execute']>[0]['input'];
export type ListNotificationsOutputType = Awaited<ReturnType<_ListNotificationsCfg['execute']>>;
export const listNotifications = createCaller<ListNotificationsInputType, ListNotificationsOutputType>('listNotifications');

type _ListPathEnrollmentsCfg = typeof _ListPathEnrollmentsEp;
export type ListPathEnrollmentsInputType = NonNullable<_ListPathEnrollmentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPathEnrollmentsCfg['execute']>[0]['input'];
export type ListPathEnrollmentsOutputType = Awaited<ReturnType<_ListPathEnrollmentsCfg['execute']>>;
export const listPathEnrollments = createCaller<ListPathEnrollmentsInputType, ListPathEnrollmentsOutputType>('listPathEnrollments');

type _ListPeopleCfg = typeof _ListPeopleEp;
export type ListPeopleInputType = NonNullable<_ListPeopleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPeopleCfg['execute']>[0]['input'];
export type ListPeopleOutputType = Awaited<ReturnType<_ListPeopleCfg['execute']>>;
export const listPeople = createCaller<ListPeopleInputType, ListPeopleOutputType>('listPeople');

type _ListPersonActivityCfg = typeof _ListPersonActivityEp;
export type ListPersonActivityInputType = NonNullable<_ListPersonActivityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPersonActivityCfg['execute']>[0]['input'];
export type ListPersonActivityOutputType = Awaited<ReturnType<_ListPersonActivityCfg['execute']>>;
export const listPersonActivity = createCaller<ListPersonActivityInputType, ListPersonActivityOutputType>('listPersonActivity');

type _ListRulesCfg = typeof _ListRulesEp;
export type ListRulesInputType = NonNullable<_ListRulesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListRulesCfg['execute']>[0]['input'];
export type ListRulesOutputType = Awaited<ReturnType<_ListRulesCfg['execute']>>;
export const listRules = createCaller<ListRulesInputType, ListRulesOutputType>('listRules');

type _ListSessionsCfg = typeof _ListSessionsEp;
export type ListSessionsInputType = NonNullable<_ListSessionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSessionsCfg['execute']>[0]['input'];
export type ListSessionsOutputType = Awaited<ReturnType<_ListSessionsCfg['execute']>>;
export const listSessions = createCaller<ListSessionsInputType, ListSessionsOutputType>('listSessions');

type _ListSubmissionsCfg = typeof _ListSubmissionsEp;
export type ListSubmissionsInputType = NonNullable<_ListSubmissionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSubmissionsCfg['execute']>[0]['input'];
export type ListSubmissionsOutputType = Awaited<ReturnType<_ListSubmissionsCfg['execute']>>;
export const listSubmissions = createCaller<ListSubmissionsInputType, ListSubmissionsOutputType>('listSubmissions');

type _PreviewRuleCfg = typeof _PreviewRuleEp;
export type PreviewRuleInputType = NonNullable<_PreviewRuleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PreviewRuleCfg['execute']>[0]['input'];
export type PreviewRuleOutputType = Awaited<ReturnType<_PreviewRuleCfg['execute']>>;
export const previewRule = createCaller<PreviewRuleInputType, PreviewRuleOutputType>('previewRule');

type _ReorderOutlineCfg = typeof _ReorderOutlineEp;
export type ReorderOutlineInputType = NonNullable<_ReorderOutlineCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReorderOutlineCfg['execute']>[0]['input'];
export type ReorderOutlineOutputType = Awaited<ReturnType<_ReorderOutlineCfg['execute']>>;
export const reorderOutline = createCaller<ReorderOutlineInputType, ReorderOutlineOutputType>('reorderOutline');

type _RunRuleCfg = typeof _RunRuleEp;
export type RunRuleInputType = NonNullable<_RunRuleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RunRuleCfg['execute']>[0]['input'];
export type RunRuleOutputType = Awaited<ReturnType<_RunRuleCfg['execute']>>;
export const runRule = createCaller<RunRuleInputType, RunRuleOutputType>('runRule');

type _SaveCategoryCfg = typeof _SaveCategoryEp;
export type SaveCategoryInputType = NonNullable<_SaveCategoryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveCategoryCfg['execute']>[0]['input'];
export type SaveCategoryOutputType = Awaited<ReturnType<_SaveCategoryCfg['execute']>>;
export const saveCategory = createCaller<SaveCategoryInputType, SaveCategoryOutputType>('saveCategory');

type _SaveCommentCfg = typeof _SaveCommentEp;
export type SaveCommentInputType = NonNullable<_SaveCommentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveCommentCfg['execute']>[0]['input'];
export type SaveCommentOutputType = Awaited<ReturnType<_SaveCommentCfg['execute']>>;
export const saveComment = createCaller<SaveCommentInputType, SaveCommentOutputType>('saveComment');

type _SaveCourseCfg = typeof _SaveCourseEp;
export type SaveCourseInputType = NonNullable<_SaveCourseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveCourseCfg['execute']>[0]['input'];
export type SaveCourseOutputType = Awaited<ReturnType<_SaveCourseCfg['execute']>>;
export const saveCourse = createCaller<SaveCourseInputType, SaveCourseOutputType>('saveCourse');

type _SaveGroupCfg = typeof _SaveGroupEp;
export type SaveGroupInputType = NonNullable<_SaveGroupCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveGroupCfg['execute']>[0]['input'];
export type SaveGroupOutputType = Awaited<ReturnType<_SaveGroupCfg['execute']>>;
export const saveGroup = createCaller<SaveGroupInputType, SaveGroupOutputType>('saveGroup');

type _SaveLessonCfg = typeof _SaveLessonEp;
export type SaveLessonInputType = NonNullable<_SaveLessonCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveLessonCfg['execute']>[0]['input'];
export type SaveLessonOutputType = Awaited<ReturnType<_SaveLessonCfg['execute']>>;
export const saveLesson = createCaller<SaveLessonInputType, SaveLessonOutputType>('saveLesson');

type _SavePathCfg = typeof _SavePathEp;
export type SavePathInputType = NonNullable<_SavePathCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePathCfg['execute']>[0]['input'];
export type SavePathOutputType = Awaited<ReturnType<_SavePathCfg['execute']>>;
export const savePath = createCaller<SavePathInputType, SavePathOutputType>('savePath');

type _SavePersonCfg = typeof _SavePersonEp;
export type SavePersonInputType = NonNullable<_SavePersonCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePersonCfg['execute']>[0]['input'];
export type SavePersonOutputType = Awaited<ReturnType<_SavePersonCfg['execute']>>;
export const savePerson = createCaller<SavePersonInputType, SavePersonOutputType>('savePerson');

type _SaveProfileCfg = typeof _SaveProfileEp;
export type SaveProfileInputType = NonNullable<_SaveProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveProfileCfg['execute']>[0]['input'];
export type SaveProfileOutputType = Awaited<ReturnType<_SaveProfileCfg['execute']>>;
export const saveProfile = createCaller<SaveProfileInputType, SaveProfileOutputType>('saveProfile');

type _SaveRuleCfg = typeof _SaveRuleEp;
export type SaveRuleInputType = NonNullable<_SaveRuleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveRuleCfg['execute']>[0]['input'];
export type SaveRuleOutputType = Awaited<ReturnType<_SaveRuleCfg['execute']>>;
export const saveRule = createCaller<SaveRuleInputType, SaveRuleOutputType>('saveRule');

type _SaveSectionCfg = typeof _SaveSectionEp;
export type SaveSectionInputType = NonNullable<_SaveSectionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSectionCfg['execute']>[0]['input'];
export type SaveSectionOutputType = Awaited<ReturnType<_SaveSectionCfg['execute']>>;
export const saveSection = createCaller<SaveSectionInputType, SaveSectionOutputType>('saveSection');

type _SaveSessionCfg = typeof _SaveSessionEp;
export type SaveSessionInputType = NonNullable<_SaveSessionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSessionCfg['execute']>[0]['input'];
export type SaveSessionOutputType = Awaited<ReturnType<_SaveSessionCfg['execute']>>;
export const saveSession = createCaller<SaveSessionInputType, SaveSessionOutputType>('saveSession');

type _SaveSettingsCfg = typeof _SaveSettingsEp;
export type SaveSettingsInputType = NonNullable<_SaveSettingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveSettingsCfg['execute']>[0]['input'];
export type SaveSettingsOutputType = Awaited<ReturnType<_SaveSettingsCfg['execute']>>;
export const saveSettings = createCaller<SaveSettingsInputType, SaveSettingsOutputType>('saveSettings');

type _SaveTemplateCfg = typeof _SaveTemplateEp;
export type SaveTemplateInputType = NonNullable<_SaveTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTemplateCfg['execute']>[0]['input'];
export type SaveTemplateOutputType = Awaited<ReturnType<_SaveTemplateCfg['execute']>>;
export const saveTemplate = createCaller<SaveTemplateInputType, SaveTemplateOutputType>('saveTemplate');

type _SaveViewCfg = typeof _SaveViewEp;
export type SaveViewInputType = NonNullable<_SaveViewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveViewCfg['execute']>[0]['input'];
export type SaveViewOutputType = Awaited<ReturnType<_SaveViewCfg['execute']>>;
export const saveView = createCaller<SaveViewInputType, SaveViewOutputType>('saveView');

type _SearchCfg = typeof _SearchEp;
export type SearchInputType = NonNullable<_SearchCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SearchCfg['execute']>[0]['input'];
export type SearchOutputType = Awaited<ReturnType<_SearchCfg['execute']>>;
export const search = createCaller<SearchInputType, SearchOutputType>('search');

type _SearchPeopleCfg = typeof _SearchPeopleEp;
export type SearchPeopleInputType = NonNullable<_SearchPeopleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SearchPeopleCfg['execute']>[0]['input'];
export type SearchPeopleOutputType = Awaited<ReturnType<_SearchPeopleCfg['execute']>>;
export const searchPeople = createCaller<SearchPeopleInputType, SearchPeopleOutputType>('searchPeople');

type _SeedWorkspaceCfg = typeof _SeedWorkspaceEp;
export type SeedWorkspaceInputType = NonNullable<_SeedWorkspaceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SeedWorkspaceCfg['execute']>[0]['input'];
export type SeedWorkspaceOutputType = Awaited<ReturnType<_SeedWorkspaceCfg['execute']>>;
export const seedWorkspace = createCaller<SeedWorkspaceInputType, SeedWorkspaceOutputType>('seedWorkspace');

type _SendRemindersCfg = typeof _SendRemindersEp;
export type SendRemindersInputType = NonNullable<_SendRemindersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendRemindersCfg['execute']>[0]['input'];
export type SendRemindersOutputType = Awaited<ReturnType<_SendRemindersCfg['execute']>>;
export const sendReminders = createCaller<SendRemindersInputType, SendRemindersOutputType>('sendReminders');

type _SendTestEmailCfg = typeof _SendTestEmailEp;
export type SendTestEmailInputType = NonNullable<_SendTestEmailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendTestEmailCfg['execute']>[0]['input'];
export type SendTestEmailOutputType = Awaited<ReturnType<_SendTestEmailCfg['execute']>>;
export const sendTestEmail = createCaller<SendTestEmailInputType, SendTestEmailOutputType>('sendTestEmail');

type _SetGroupMembersCfg = typeof _SetGroupMembersEp;
export type SetGroupMembersInputType = NonNullable<_SetGroupMembersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SetGroupMembersCfg['execute']>[0]['input'];
export type SetGroupMembersOutputType = Awaited<ReturnType<_SetGroupMembersCfg['execute']>>;
export const setGroupMembers = createCaller<SetGroupMembersInputType, SetGroupMembersOutputType>('setGroupMembers');

type _UpdateCertificateCfg = typeof _UpdateCertificateEp;
export type UpdateCertificateInputType = NonNullable<_UpdateCertificateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateCertificateCfg['execute']>[0]['input'];
export type UpdateCertificateOutputType = Awaited<ReturnType<_UpdateCertificateCfg['execute']>>;
export const updateCertificate = createCaller<UpdateCertificateInputType, UpdateCertificateOutputType>('updateCertificate');

type _UpdateEnrollmentsCfg = typeof _UpdateEnrollmentsEp;
export type UpdateEnrollmentsInputType = NonNullable<_UpdateEnrollmentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateEnrollmentsCfg['execute']>[0]['input'];
export type UpdateEnrollmentsOutputType = Awaited<ReturnType<_UpdateEnrollmentsCfg['execute']>>;
export const updateEnrollments = createCaller<UpdateEnrollmentsInputType, UpdateEnrollmentsOutputType>('updateEnrollments');

type _UpdateNotificationsCfg = typeof _UpdateNotificationsEp;
export type UpdateNotificationsInputType = NonNullable<_UpdateNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateNotificationsCfg['execute']>[0]['input'];
export type UpdateNotificationsOutputType = Awaited<ReturnType<_UpdateNotificationsCfg['execute']>>;
export const updateNotifications = createCaller<UpdateNotificationsInputType, UpdateNotificationsOutputType>('updateNotifications');

type _UpdatePathEnrollmentsCfg = typeof _UpdatePathEnrollmentsEp;
export type UpdatePathEnrollmentsInputType = NonNullable<_UpdatePathEnrollmentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdatePathEnrollmentsCfg['execute']>[0]['input'];
export type UpdatePathEnrollmentsOutputType = Awaited<ReturnType<_UpdatePathEnrollmentsCfg['execute']>>;
export const updatePathEnrollments = createCaller<UpdatePathEnrollmentsInputType, UpdatePathEnrollmentsOutputType>('updatePathEnrollments');

type _UpdateRegistrationsCfg = typeof _UpdateRegistrationsEp;
export type UpdateRegistrationsInputType = NonNullable<_UpdateRegistrationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateRegistrationsCfg['execute']>[0]['input'];
export type UpdateRegistrationsOutputType = Awaited<ReturnType<_UpdateRegistrationsCfg['execute']>>;
export const updateRegistrations = createCaller<UpdateRegistrationsInputType, UpdateRegistrationsOutputType>('updateRegistrations');


export const api = {
  aiDraftFeedback,
  aiGenerateCourse,
  aiGenerateQuiz,
  bootstrap,
  bulkUpdatePeople,
  certificatePdf,
  clearDemoData,
  deleteLesson,
  duplicateCourse,
  enroll,
  exportReport,
  getComplianceReport,
  getCourse,
  getCourseOverview,
  getCourseReport,
  getEnrollment,
  getGroup,
  getHome,
  getPath,
  getPerson,
  getQuizReport,
  getReports,
  getSession,
  getSubmission,
  gradeSubmission,
  importPeople,
  listCertificates,
  listDiscussions,
  listEnrollments,
  listGroups,
  listNotifications,
  listPathEnrollments,
  listPeople,
  listPersonActivity,
  listRules,
  listSessions,
  listSubmissions,
  previewRule,
  reorderOutline,
  runRule,
  saveCategory,
  saveComment,
  saveCourse,
  saveGroup,
  saveLesson,
  savePath,
  savePerson,
  saveProfile,
  saveRule,
  saveSection,
  saveSession,
  saveSettings,
  saveTemplate,
  saveView,
  search,
  searchPeople,
  seedWorkspace,
  sendReminders,
  sendTestEmail,
  setGroupMembers,
  updateCertificate,
  updateEnrollments,
  updateNotifications,
  updatePathEnrollments,
  updateRegistrations,
};
