// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Settings" table, as it is read back. */
export type SettingsRecordType = {
  id: string;
  /** Primary field. "Organization Name" */
  organizationName?: string;
  logoUrl?: string;
  websiteUrl?: string;
  supportEmail?: string;
  brandColor?: string;
  academyName?: string;
  academyHeadline?: string;
  academyIntro?: string;
  signInPolicy?: "Invited only" | "Allowed domains" | "Anyone" | string;
  allowedDomains?: string;
  selfEnrollment?: boolean;
  leaderboardEnabled?: boolean;
  discussionsEnabled?: boolean;
  defaultStaffRole?: "Instructor" | "Learner" | string;
  /** "Reminder Days Before". 0 decimal places, format: local (e.g. 1,000,000.50) */
  reminderDaysBefore?: number;
  escalateOverdue?: boolean;
  emailSignature?: string;
  certificateTitle?: string;
  certificateSignatory?: string;
  certificateSignatoryTitle?: string;
  timezone?: string;
  /** "Seeded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  seededAt?: string;
  learnUrl?: string;
  adminAppUrl?: string;
};

/** What you may write when creating or updating a record in the "Settings" table. */
export type SettingsRecordInput = {
  organizationName: string | null;
  logoUrl: string | null;
  websiteUrl: string | null;
  supportEmail: string | null;
  brandColor: string | null;
  academyName: string | null;
  academyHeadline: string | null;
  academyIntro: string | null;
  signInPolicy: "Invited only" | "Allowed domains" | "Anyone" | string | null;
  allowedDomains: string | null;
  selfEnrollment: string | boolean | null;
  leaderboardEnabled: string | boolean | null;
  discussionsEnabled: string | boolean | null;
  defaultStaffRole: "Instructor" | "Learner" | string | null;
  reminderDaysBefore: string | number | null;
  escalateOverdue: string | boolean | null;
  emailSignature: string | null;
  certificateTitle: string | null;
  certificateSignatory: string | null;
  certificateSignatoryTitle: string | null;
  timezone: string | null;
  seededAt: string | Date | null;
  learnUrl: string | null;
  adminAppUrl: string | null;
};

/** A record in the "People" table, as it is read back. */
export type PeopleRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  role?: "Admin" | "Instructor" | "Learner" | string;
  status?: "Active" | "Invited" | "Deactivated" | string;
  title?: string;
  managerId?: string;
  /** "Hire Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  hireDate?: string;
  externalId?: string;
  avatarUrl?: string;
  color?: string;
  bio?: string;
  muteEmails?: boolean;
  /** "Invited At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  invitedAt?: string;
  /** "Last Seen At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastSeenAt?: string;
  /** "Last Learned At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastLearnedAt?: string;
  /** "Deactivated At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  deactivatedAt?: string;
};

/** What you may write when creating or updating a record in the "People" table. */
export type PeopleRecordInput = {
  name: string | null;
  email: string | null;
  role: "Admin" | "Instructor" | "Learner" | string | null;
  status: "Active" | "Invited" | "Deactivated" | string | null;
  title: string | null;
  managerId: string | null;
  hireDate: string | Date | null;
  externalId: string | null;
  avatarUrl: string | null;
  color: string | null;
  bio: string | null;
  muteEmails: string | boolean | null;
  invitedAt: string | Date | null;
  lastSeenAt: string | Date | null;
  lastLearnedAt: string | Date | null;
  deactivatedAt: string | Date | null;
};

/** A record in the "Groups" table, as it is read back. */
export type GroupsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  kind?: "Department" | "Team" | "Location" | "Cohort" | "Customer" | "Partner" | string;
  description?: string;
  color?: string;
  ownerId?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Groups" table. */
export type GroupsRecordInput = {
  name: string | null;
  kind: "Department" | "Team" | "Location" | "Cohort" | "Customer" | "Partner" | string | null;
  description: string | null;
  color: string | null;
  ownerId: string | null;
  position: string | number | null;
};

/** A record in the "Group Members" table, as it is read back. */
export type GroupMembersRecordType = {
  id: string;
  /** Primary field. "Group Id" */
  groupId?: string;
  personId?: string;
  /** "Added At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  addedAt?: string;
  addedById?: string;
};

/** What you may write when creating or updating a record in the "Group Members" table. */
export type GroupMembersRecordInput = {
  groupId: string | null;
  personId: string | null;
  addedAt: string | Date | null;
  addedById: string | null;
};

/** A record in the "Categories" table, as it is read back. */
export type CategoriesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  description?: string;
  color?: string;
  icon?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Categories" table. */
export type CategoriesRecordInput = {
  name: string | null;
  description: string | null;
  color: string | null;
  icon: string | null;
  position: string | number | null;
};

/** A record in the "Courses" table, as it is read back. */
export type CoursesRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  slug?: string;
  summary?: string;
  description?: string;
  objectives?: string;
  coverImageUrl?: string;
  icon?: string;
  color?: string;
  categoryId?: string;
  level?: "Beginner" | "Intermediate" | "Advanced" | string;
  status?: "Draft" | "Published" | "Archived" | string;
  visibility?: "Catalog" | "Private" | string;
  ownerId?: string;
  instructorIds?: string;
  sequential?: boolean;
  /** "Estimated Minutes". 0 decimal places, format: local (e.g. 1,000,000.50) */
  estimatedMinutes?: number;
  /** "Due Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  dueDays?: number;
  certificateEnabled?: boolean;
  /** "Certificate Validity Months". 0 decimal places, format: local (e.g. 1,000,000.50) */
  certificateValidityMonths?: number;
  skills?: string;
  /** "Published At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  publishedAt?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Courses" table. */
export type CoursesRecordInput = {
  title: string | null;
  slug: string | null;
  summary: string | null;
  description: string | null;
  objectives: string | null;
  coverImageUrl: string | null;
  icon: string | null;
  color: string | null;
  categoryId: string | null;
  level: "Beginner" | "Intermediate" | "Advanced" | string | null;
  status: "Draft" | "Published" | "Archived" | string | null;
  visibility: "Catalog" | "Private" | string | null;
  ownerId: string | null;
  instructorIds: string | null;
  sequential: string | boolean | null;
  estimatedMinutes: string | number | null;
  dueDays: string | number | null;
  certificateEnabled: string | boolean | null;
  certificateValidityMonths: string | number | null;
  skills: string | null;
  publishedAt: string | Date | null;
  position: string | number | null;
};

/** A record in the "Sections" table, as it is read back. */
export type SectionsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  courseId?: string;
  description?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Sections" table. */
export type SectionsRecordInput = {
  title: string | null;
  courseId: string | null;
  description: string | null;
  position: string | number | null;
};

/** A record in the "Lessons" table, as it is read back. */
export type LessonsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  courseId?: string;
  sectionId?: string;
  type?: "Article" | "Video" | "Quiz" | "Assignment" | "File" | "Embed" | "Live session" | "Checklist" | string;
  body?: string;
  mediaUrl?: string;
  mediaName?: string;
  settings?: string;
  /** "Duration Minutes". 0 decimal places, format: local (e.g. 1,000,000.50) */
  durationMinutes?: number;
  optional?: boolean;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Lessons" table. */
export type LessonsRecordInput = {
  title: string | null;
  courseId: string | null;
  sectionId: string | null;
  type: "Article" | "Video" | "Quiz" | "Assignment" | "File" | "Embed" | "Live session" | "Checklist" | string | null;
  body: string | null;
  mediaUrl: string | null;
  mediaName: string | null;
  settings: string | null;
  durationMinutes: string | number | null;
  optional: string | boolean | null;
  position: string | number | null;
};

/** A record in the "Paths" table, as it is read back. */
export type PathsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  slug?: string;
  summary?: string;
  description?: string;
  coverImageUrl?: string;
  icon?: string;
  color?: string;
  categoryId?: string;
  status?: "Draft" | "Published" | "Archived" | string;
  visibility?: "Catalog" | "Private" | string;
  ownerId?: string;
  sequential?: boolean;
  /** "Due Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  dueDays?: number;
  certificateEnabled?: boolean;
  /** "Certificate Validity Months". 0 decimal places, format: local (e.g. 1,000,000.50) */
  certificateValidityMonths?: number;
  /** "Published At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  publishedAt?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Paths" table. */
export type PathsRecordInput = {
  title: string | null;
  slug: string | null;
  summary: string | null;
  description: string | null;
  coverImageUrl: string | null;
  icon: string | null;
  color: string | null;
  categoryId: string | null;
  status: "Draft" | "Published" | "Archived" | string | null;
  visibility: "Catalog" | "Private" | string | null;
  ownerId: string | null;
  sequential: string | boolean | null;
  dueDays: string | number | null;
  certificateEnabled: string | boolean | null;
  certificateValidityMonths: string | number | null;
  publishedAt: string | Date | null;
  position: string | number | null;
};

/** A record in the "Path Courses" table, as it is read back. */
export type PathCoursesRecordType = {
  id: string;
  /** Primary field. "Path Id" */
  pathId?: string;
  courseId?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
  optional?: boolean;
};

/** What you may write when creating or updating a record in the "Path Courses" table. */
export type PathCoursesRecordInput = {
  pathId: string | null;
  courseId: string | null;
  position: string | number | null;
  optional: string | boolean | null;
};

/** A record in the "Enrollments" table, as it is read back. */
export type EnrollmentsRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  personId?: string;
  courseId?: string;
  pathEnrollmentId?: string;
  ruleId?: string;
  source?: "Assigned" | "Self-enrolled" | "Automatic" | "Path" | string;
  assignedById?: string;
  status?: "Not started" | "In progress" | "Completed" | "Withdrawn" | string;
  /** "Progress". 0 decimal places, format: local (e.g. 1,000,000.50) */
  progress?: number;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  /** "Enrolled At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  enrolledAt?: string;
  /** "Started At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startedAt?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  /** "Last Activity At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActivityAt?: string;
  currentLessonId?: string;
  /** "Score". 0 decimal places, format: local (e.g. 1,000,000.50) */
  score?: number;
  /** "Time Spent Seconds". 0 decimal places, format: local (e.g. 1,000,000.50) */
  timeSpentSeconds?: number;
  certificateId?: string;
  /** "Cycle". 0 decimal places, format: local (e.g. 1,000,000.50) */
  cycle?: number;
  /** "Reminded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  remindedAt?: string;
  /** "Overdue Notified At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  overdueNotifiedAt?: string;
  /** "Rating". 0 decimal places, format: local (e.g. 1,000,000.50) */
  rating?: number;
  review?: string;
  /** "Rated At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  ratedAt?: string;
  /** "Withdrawn At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  withdrawnAt?: string;
};

/** What you may write when creating or updating a record in the "Enrollments" table. */
export type EnrollmentsRecordInput = {
  label: string | null;
  personId: string | null;
  courseId: string | null;
  pathEnrollmentId: string | null;
  ruleId: string | null;
  source: "Assigned" | "Self-enrolled" | "Automatic" | "Path" | string | null;
  assignedById: string | null;
  status: "Not started" | "In progress" | "Completed" | "Withdrawn" | string | null;
  progress: string | number | null;
  dueDate: string | Date | null;
  enrolledAt: string | Date | null;
  startedAt: string | Date | null;
  completedAt: string | Date | null;
  lastActivityAt: string | Date | null;
  currentLessonId: string | null;
  score: string | number | null;
  timeSpentSeconds: string | number | null;
  certificateId: string | null;
  cycle: string | number | null;
  remindedAt: string | Date | null;
  overdueNotifiedAt: string | Date | null;
  rating: string | number | null;
  review: string | null;
  ratedAt: string | Date | null;
  withdrawnAt: string | Date | null;
};

/** A record in the "Path Enrollments" table, as it is read back. */
export type PathEnrollmentsRecordType = {
  id: string;
  /** Primary field. "Label" */
  label?: string;
  personId?: string;
  pathId?: string;
  ruleId?: string;
  source?: "Assigned" | "Self-enrolled" | "Automatic" | string;
  assignedById?: string;
  status?: "Not started" | "In progress" | "Completed" | "Withdrawn" | string;
  /** "Progress". 0 decimal places, format: local (e.g. 1,000,000.50) */
  progress?: number;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  /** "Enrolled At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  enrolledAt?: string;
  /** "Started At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startedAt?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  certificateId?: string;
  /** "Cycle". 0 decimal places, format: local (e.g. 1,000,000.50) */
  cycle?: number;
  /** "Reminded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  remindedAt?: string;
  /** "Overdue Notified At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  overdueNotifiedAt?: string;
  /** "Withdrawn At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  withdrawnAt?: string;
};

/** What you may write when creating or updating a record in the "Path Enrollments" table. */
export type PathEnrollmentsRecordInput = {
  label: string | null;
  personId: string | null;
  pathId: string | null;
  ruleId: string | null;
  source: "Assigned" | "Self-enrolled" | "Automatic" | string | null;
  assignedById: string | null;
  status: "Not started" | "In progress" | "Completed" | "Withdrawn" | string | null;
  progress: string | number | null;
  dueDate: string | Date | null;
  enrolledAt: string | Date | null;
  startedAt: string | Date | null;
  completedAt: string | Date | null;
  certificateId: string | null;
  cycle: string | number | null;
  remindedAt: string | Date | null;
  overdueNotifiedAt: string | Date | null;
  withdrawnAt: string | Date | null;
};

/** A record in the "Lesson Progress" table, as it is read back. */
export type LessonProgressRecordType = {
  id: string;
  /** Primary field. "Enrollment Id" */
  enrollmentId?: string;
  personId?: string;
  courseId?: string;
  lessonId?: string;
  status?: "In progress" | "Completed" | string;
  /** "Started At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startedAt?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  /** "Time Spent Seconds". 0 decimal places, format: local (e.g. 1,000,000.50) */
  timeSpentSeconds?: number;
  /** "Score". 0 decimal places, format: local (e.g. 1,000,000.50) */
  score?: number;
  /** "Attempts". 0 decimal places, format: local (e.g. 1,000,000.50) */
  attempts?: number;
  state?: string;
};

/** What you may write when creating or updating a record in the "Lesson Progress" table. */
export type LessonProgressRecordInput = {
  enrollmentId: string | null;
  personId: string | null;
  courseId: string | null;
  lessonId: string | null;
  status: "In progress" | "Completed" | string | null;
  startedAt: string | Date | null;
  completedAt: string | Date | null;
  timeSpentSeconds: string | number | null;
  score: string | number | null;
  attempts: string | number | null;
  state: string | null;
};

/** A record in the "Quiz Attempts" table, as it is read back. */
export type QuizAttemptsRecordType = {
  id: string;
  /** Primary field. "Enrollment Id" */
  enrollmentId?: string;
  personId?: string;
  courseId?: string;
  lessonId?: string;
  /** "Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  number?: number;
  answers?: string;
  /** "Score". 0 decimal places, format: local (e.g. 1,000,000.50) */
  score?: number;
  passed?: boolean;
  /** "Started At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startedAt?: string;
  /** "Submitted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  submittedAt?: string;
};

/** What you may write when creating or updating a record in the "Quiz Attempts" table. */
export type QuizAttemptsRecordInput = {
  enrollmentId: string | null;
  personId: string | null;
  courseId: string | null;
  lessonId: string | null;
  number: string | number | null;
  answers: string | null;
  score: string | number | null;
  passed: string | boolean | null;
  startedAt: string | Date | null;
  submittedAt: string | Date | null;
};

/** A record in the "Submissions" table, as it is read back. */
export type SubmissionsRecordType = {
  id: string;
  /** Primary field. "Enrollment Id" */
  enrollmentId?: string;
  personId?: string;
  courseId?: string;
  lessonId?: string;
  /** "Attempt". 0 decimal places, format: local (e.g. 1,000,000.50) */
  attempt?: number;
  body?: string;
  files?: string;
  status?: "Submitted" | "Passed" | "Needs revision" | string;
  /** "Grade". 0 decimal places, format: local (e.g. 1,000,000.50) */
  grade?: number;
  feedback?: string;
  gradedById?: string;
  /** "Submitted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  submittedAt?: string;
  /** "Graded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  gradedAt?: string;
};

/** What you may write when creating or updating a record in the "Submissions" table. */
export type SubmissionsRecordInput = {
  enrollmentId: string | null;
  personId: string | null;
  courseId: string | null;
  lessonId: string | null;
  attempt: string | number | null;
  body: string | null;
  files: string | null;
  status: "Submitted" | "Passed" | "Needs revision" | string | null;
  grade: string | number | null;
  feedback: string | null;
  gradedById: string | null;
  submittedAt: string | Date | null;
  gradedAt: string | Date | null;
};

/** A record in the "Certificates" table, as it is read back. */
export type CertificatesRecordType = {
  id: string;
  /** Primary field. "Credential Id" */
  credentialId?: string;
  personId?: string;
  courseId?: string;
  pathId?: string;
  enrollmentId?: string;
  title?: string;
  recipientName?: string;
  /** "Issued At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  issuedAt?: string;
  /** "Expires At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  expiresAt?: string;
  status?: "Active" | "Revoked" | string;
  /** "Revoked At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  revokedAt?: string;
  revokedReason?: string;
  issuedById?: string;
  /** "Score". 0 decimal places, format: local (e.g. 1,000,000.50) */
  score?: number;
};

/** What you may write when creating or updating a record in the "Certificates" table. */
export type CertificatesRecordInput = {
  credentialId: string | null;
  personId: string | null;
  courseId: string | null;
  pathId: string | null;
  enrollmentId: string | null;
  title: string | null;
  recipientName: string | null;
  issuedAt: string | Date | null;
  expiresAt: string | Date | null;
  status: "Active" | "Revoked" | string | null;
  revokedAt: string | Date | null;
  revokedReason: string | null;
  issuedById: string | null;
  score: string | number | null;
};

/** A record in the "Sessions" table, as it is read back. */
export type SessionsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  courseId?: string;
  lessonId?: string;
  description?: string;
  /** "Starts At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startsAt?: string;
  /** "Ends At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  endsAt?: string;
  timezone?: string;
  location?: string;
  meetingUrl?: string;
  recordingUrl?: string;
  /** "Capacity". 0 decimal places, format: local (e.g. 1,000,000.50) */
  capacity?: number;
  instructorId?: string;
  status?: "Scheduled" | "Cancelled" | string;
};

/** What you may write when creating or updating a record in the "Sessions" table. */
export type SessionsRecordInput = {
  title: string | null;
  courseId: string | null;
  lessonId: string | null;
  description: string | null;
  startsAt: string | Date | null;
  endsAt: string | Date | null;
  timezone: string | null;
  location: string | null;
  meetingUrl: string | null;
  recordingUrl: string | null;
  capacity: string | number | null;
  instructorId: string | null;
  status: "Scheduled" | "Cancelled" | string | null;
};

/** A record in the "Registrations" table, as it is read back. */
export type RegistrationsRecordType = {
  id: string;
  /** Primary field. "Session Id" */
  sessionId?: string;
  personId?: string;
  status?: "Registered" | "Waitlisted" | "Attended" | "Absent" | "Cancelled" | string;
  /** "Registered At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  registeredAt?: string;
  /** "Checked In At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  checkedInAt?: string;
  /** "Reminded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  remindedAt?: string;
};

/** What you may write when creating or updating a record in the "Registrations" table. */
export type RegistrationsRecordInput = {
  sessionId: string | null;
  personId: string | null;
  status: "Registered" | "Waitlisted" | "Attended" | "Absent" | "Cancelled" | string | null;
  registeredAt: string | Date | null;
  checkedInAt: string | Date | null;
  remindedAt: string | Date | null;
};

/** A record in the "Assignment Rules" table, as it is read back. */
export type AssignmentRulesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  targetType?: "Course" | "Path" | string;
  courseId?: string;
  pathId?: string;
  audience?: "Everyone" | "Groups" | "People" | string;
  groupIds?: string;
  personIds?: string;
  dueMode?: "None" | "Relative" | "Fixed" | string;
  /** "Due Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  dueDays?: number;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  /** "Recurrence Months". 0 decimal places, format: local (e.g. 1,000,000.50) */
  recurrenceMonths?: number;
  includeFutureMembers?: boolean;
  sendEmail?: boolean;
  status?: "Active" | "Paused" | "Archived" | string;
  createdById?: string;
  /** "Last Run At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastRunAt?: string;
};

/** What you may write when creating or updating a record in the "Assignment Rules" table. */
export type AssignmentRulesRecordInput = {
  name: string | null;
  targetType: "Course" | "Path" | string | null;
  courseId: string | null;
  pathId: string | null;
  audience: "Everyone" | "Groups" | "People" | string | null;
  groupIds: string | null;
  personIds: string | null;
  dueMode: "None" | "Relative" | "Fixed" | string | null;
  dueDays: string | number | null;
  dueDate: string | Date | null;
  recurrenceMonths: string | number | null;
  includeFutureMembers: string | boolean | null;
  sendEmail: string | boolean | null;
  status: "Active" | "Paused" | "Archived" | string | null;
  createdById: string | null;
  lastRunAt: string | Date | null;
};

/** A record in the "Comments" table, as it is read back. */
export type CommentsRecordType = {
  id: string;
  /** Primary field. "Body" */
  body?: string;
  courseId?: string;
  lessonId?: string;
  personId?: string;
  parentId?: string;
  /** "Posted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  postedAt?: string;
  /** "Edited At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  editedAt?: string;
  pinned?: boolean;
  /** "Resolved At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  resolvedAt?: string;
};

/** What you may write when creating or updating a record in the "Comments" table. */
export type CommentsRecordInput = {
  body: string | null;
  courseId: string | null;
  lessonId: string | null;
  personId: string | null;
  parentId: string | null;
  postedAt: string | Date | null;
  editedAt: string | Date | null;
  pinned: string | boolean | null;
  resolvedAt: string | Date | null;
};

/** A record in the "Notifications" table, as it is read back. */
export type NotificationsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  body?: string;
  type?: string;
  app?: "Admin" | "Learn" | string;
  recipientId?: string;
  actorId?: string;
  courseId?: string;
  pathId?: string;
  link?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
  /** "Read At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  readAt?: string;
  /** "Archived At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  archivedAt?: string;
};

/** What you may write when creating or updating a record in the "Notifications" table. */
export type NotificationsRecordInput = {
  title: string | null;
  body: string | null;
  type: string | null;
  app: "Admin" | "Learn" | string | null;
  recipientId: string | null;
  actorId: string | null;
  courseId: string | null;
  pathId: string | null;
  link: string | null;
  occurredAt: string | Date | null;
  readAt: string | Date | null;
  archivedAt: string | Date | null;
};

/** A record in the "Activity" table, as it is read back. */
export type ActivityRecordType = {
  id: string;
  /** Primary field. "Type" */
  type?: string;
  personId?: string;
  actorId?: string;
  courseId?: string;
  pathId?: string;
  lessonId?: string;
  enrollmentId?: string;
  data?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
};

/** What you may write when creating or updating a record in the "Activity" table. */
export type ActivityRecordInput = {
  type: string | null;
  personId: string | null;
  actorId: string | null;
  courseId: string | null;
  pathId: string | null;
  lessonId: string | null;
  enrollmentId: string | null;
  data: string | null;
  occurredAt: string | Date | null;
};

/** A record in the "Email Templates" table, as it is read back. */
export type EmailTemplatesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  subject?: string;
  body?: string;
  trigger?: "Course assigned" | "Path assigned" | "Due reminder" | "Overdue" | "Manager overdue digest" | "Certificate issued" | "Certificate expiring" | "Submission graded" | "Session registered" | "Session reminder" | "Invitation" | string;
  enabled?: boolean;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Email Templates" table. */
export type EmailTemplatesRecordInput = {
  name: string | null;
  subject: string | null;
  body: string | null;
  trigger: "Course assigned" | "Path assigned" | "Due reminder" | "Overdue" | "Manager overdue digest" | "Certificate issued" | "Certificate expiring" | "Submission graded" | "Session registered" | "Session reminder" | "Invitation" | string | null;
  enabled: string | boolean | null;
  position: string | number | null;
};

/** A record in the "Views" table, as it is read back. */
export type ViewsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  ownerId?: string;
  scope?: "Personal" | "Shared" | string;
  page?: string;
  config?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Views" table. */
export type ViewsRecordInput = {
  name: string | null;
  ownerId: string | null;
  scope: "Personal" | "Shared" | string | null;
  page: string | null;
  config: string | null;
  position: string | number | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  settings: createTableClient<SettingsRecordType, SettingsRecordInput>('Settings'), // "Settings"
  people: createTableClient<PeopleRecordType, PeopleRecordInput>('People'), // "People"
  groups: createTableClient<GroupsRecordType, GroupsRecordInput>('Groups'), // "Groups"
  groupMembers: createTableClient<GroupMembersRecordType, GroupMembersRecordInput>('GroupMembers'), // "Group Members"
  categories: createTableClient<CategoriesRecordType, CategoriesRecordInput>('Categories'), // "Categories"
  courses: createTableClient<CoursesRecordType, CoursesRecordInput>('Courses'), // "Courses"
  sections: createTableClient<SectionsRecordType, SectionsRecordInput>('Sections'), // "Sections"
  lessons: createTableClient<LessonsRecordType, LessonsRecordInput>('Lessons'), // "Lessons"
  paths: createTableClient<PathsRecordType, PathsRecordInput>('Paths'), // "Paths"
  pathCourses: createTableClient<PathCoursesRecordType, PathCoursesRecordInput>('PathCourses'), // "Path Courses"
  enrollments: createTableClient<EnrollmentsRecordType, EnrollmentsRecordInput>('Enrollments'), // "Enrollments"
  pathEnrollments: createTableClient<PathEnrollmentsRecordType, PathEnrollmentsRecordInput>('PathEnrollments'), // "Path Enrollments"
  lessonProgress: createTableClient<LessonProgressRecordType, LessonProgressRecordInput>('LessonProgress'), // "Lesson Progress"
  quizAttempts: createTableClient<QuizAttemptsRecordType, QuizAttemptsRecordInput>('QuizAttempts'), // "Quiz Attempts"
  submissions: createTableClient<SubmissionsRecordType, SubmissionsRecordInput>('Submissions'), // "Submissions"
  certificates: createTableClient<CertificatesRecordType, CertificatesRecordInput>('Certificates'), // "Certificates"
  sessions: createTableClient<SessionsRecordType, SessionsRecordInput>('Sessions'), // "Sessions"
  registrations: createTableClient<RegistrationsRecordType, RegistrationsRecordInput>('Registrations'), // "Registrations"
  assignmentRules: createTableClient<AssignmentRulesRecordType, AssignmentRulesRecordInput>('AssignmentRules'), // "Assignment Rules"
  comments: createTableClient<CommentsRecordType, CommentsRecordInput>('Comments'), // "Comments"
  notifications: createTableClient<NotificationsRecordType, NotificationsRecordInput>('Notifications'), // "Notifications"
  activity: createTableClient<ActivityRecordType, ActivityRecordInput>('Activity'), // "Activity"
  emailTemplates: createTableClient<EmailTemplatesRecordType, EmailTemplatesRecordInput>('EmailTemplates'), // "Email Templates"
  views: createTableClient<ViewsRecordType, ViewsRecordInput>('Views'), // "Views"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
